# Generated by Django 4.2.9 on 2026-02-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("meta", "Meta Ads"),
                            ("linkedin", "LinkedIn Ads"),
                            ("google_ads", "Google Ads"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(max_length=500)),
                ("status", models.CharField(default="UNKNOWN", max_length=50)),
                ("objective", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="integrations.platformconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campanha",
                "verbose_name_plural": "Campanhas",
                "ordering": ["-updated_at"],
                "unique_together": {("connection", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="CampaignMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                ("reach", models.BigIntegerField(default=0)),
                ("leads", models.BigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ctr",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Click-Through Rate (%)",
                        max_digits=8,
                    ),
                ),
                (
                    "cpc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost per Click",
                        max_digits=10,
                    ),
                ),
                (
                    "cpm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost per 1000 Impressions",
                        max_digits=10,
                    ),
                ),
                (
                    "cpl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost per Lead",
                        max_digits=10,
                    ),
                ),
                (
                    "roas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Return on Ad Spend",
                        max_digits=10,
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrica de Campanha",
                "verbose_name_plural": "Métricas de Campanhas",
                "ordering": ["-date_from"],
                "unique_together": {("campaign", "date_from", "date_to")},
            },
        ),
    ]
