# Generated by Django 4.2.9 on 2026-02-26 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("meta", "Meta Ads"),
                            ("linkedin", "LinkedIn Ads"),
                            ("google_ads", "Google Ads"),
                            ("google_sheets", "Google Sheets"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("oauth", "OAuth 2.0"),
                            ("manual", "Credenciais Manuais"),
                        ],
                        default="oauth",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome amigável para esta conexão", max_length=200
                    ),
                ),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account_id",
                    models.CharField(
                        blank=True, help_text="ID da conta de anúncios", max_length=200
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configurações extras (ex: spreadsheet_id)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conexão de Plataforma",
                "verbose_name_plural": "Conexões de Plataformas",
                "unique_together": {("user", "platform", "account_id")},
            },
        ),
    ]
