# Generated by Django 4.2.9 on 2026-02-26 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("platforms", models.JSONField(default=list)),
                (
                    "date_preset",
                    models.CharField(
                        choices=[
                            ("last_7_days", "Últimos 7 dias"),
                            ("last_14_days", "Últimos 14 dias"),
                            ("last_30_days", "Últimos 30 dias"),
                            ("this_month", "Este mês"),
                            ("last_month", "Mês passado"),
                            ("custom", "Personalizado"),
                        ],
                        default="last_30_days",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "ordering": ["-created_at"],
            },
        ),
    ]
